export { default as Description } from "@/components/shared/profile/description"
export { default as User } from "@/components/shared/profile/user"
export { default as Banner } from "@/components/shared/profile/banner"
export { default as Publications } from "@/components/shared/profile/publications/publications"
// export { default as Publication } from "@/components/shared/profile/publications/post"